apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gr4jwdcf8-nodejs 
  janus-idp.io/tekton: gr4jwdcf8-nodejs
  backstage.io/kubernetes-id: gr4jwdcf8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gr4jwdcf8-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml